# Generated by Django 3.2.6 on 2021-08-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewdout', '0002_alter_check_in_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='cost',
            field=models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$'), (5, '$$$$$')]),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Meh'), (3, 'Good'), (4, 'Great'), (5, 'Phenomenal')]),
        ),
    ]
